dist: focal
language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

before_script:
  - echo "$DEPLOY_KEY" | base64 -d > ${HOME}/gcloud-key.json
  - curl -sSL https://sdk.cloud.google.com | bash -s -- --disable-prompts --install-dir=$HOME --bash-completion=false
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
  - gcloud config set project django-demo-456022

script:
  - python manage.py test

deploy:
  provider: script
  script: gcloud app deploy app.yaml --quiet
  on:
    branch: main
