dist: focal
language: python
python:
  - "3.9"

before_install:
  - gem install dpl -v 1.10.16


install:
  - pip install -r requirements.txt

before_script:
  - echo "$DEPLOY_KEY" | base64 -d > ${HOME}/gcloud-key.json
  - curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-437.0.1-linux-x86_64.tar.gz
  - tar -xzf google-cloud-sdk-437.0.1-linux-x86_64.tar.gz
  - ./google-cloud-sdk/install.sh --quiet
  - source ./google-cloud-sdk/path.bash.inc
  - gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json
  - gcloud config set project django-demo-456022


script:
  - python manage.py test
  - |
    if [ "$TRAVIS_BRANCH" = "main" ]; then
      echo "Deploying to App Engine..."
      gcloud app deploy app.yaml --quiet
    else
      echo "Not on main branch, skipping deployment."
    fi

# deploy:
#   provider: script
#   script: gcloud app deploy app.yaml --quiet
#   skip_cleanup: true
#   on:
#     branch: main
