runtime: python39

entrypoint: gunicorn mysite.wsgi --bind :$PORT

instance_class: F1

env_variables:
  DJANGO_SETTINGS_MODULE: "mysite.settings"
  SECRET_KEY: "some-super-secret-key-here"
  # Add DB credentials if needed

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
